### ISSUE TITLE
PUT请求 报IllegalArgumentException

### ISSUE THREAD

**Issue by pandaApe** [hongyangAndroid/okhttp-utils#116]
Caused by: java.lang.IllegalArgumentException: value == null
                                                                              at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:279)
                                                                              at okhttp3.Headers$Builder.add(Headers.java:233)
                                                                              at com.zhy.http.okhttp.request.OkHttpRequest.appendHeaders(OkHttpRequest.java:82)
                                                                              at com.zhy.http.okhttp.request.OkHttpRequest.initBuilder(OkHttpRequest.java:48)
                                                                              at com.zhy.http.okhttp.request.OkHttpRequest.<init>(OkHttpRequest.java:37)

**Comment by hongyangAndroid** [comment]
由`Headers.checkNameAndValue`抛出，addHeader时，value为null.
