### ISSUE TITLE
上传文件时，文件名中包含有#号，则会报错！

### ISSUE THREAD

**Issue by jacpy** [hongyangAndroid/okhttp-utils#126]
以下是错误日志：
java.lang.StringIndexOutOfBoundsException: length=12; regionStart=9; regionLength=-4
at java.lang.String.startEndAndLength(String.java:588)
at java.lang.String.substring(String.java:1475)
at java.net.DefaultFileNameMap.getContentTypeFor(DefaultFileNameMap.java:38)
at com.zhy.http.okhttp.request.PostFormRequest.guessMimeType(PostFormRequest.java:89)
at com.zhy.http.okhttp.request.PostFormRequest.buildRequestBody(PostFormRequest.java:49)
at com.zhy.http.okhttp.request.OkHttpRequest.generateRequest(OkHttpRequest.java:68)
at com.zhy.http.okhttp.request.RequestCall.generateRequest(RequestCall.java:76)
at com.zhy.http.okhttp.request.RequestCall.buildCall(RequestCall.java:52)
at com.zhy.http.okhttp.request.RequestCall.execute(RequestCall.java:81)

解决办法如下：

private String guessMimeType(String path)
    {
        FileNameMap fileNameMap = URLConnection.getFileNameMap();
        String contentTypeFor = null;
        try {
            // 路径转义
            contentTypeFor = fileNameMap.getContentTypeFor(URLEncoder.encode(path, "UTF-8"));
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }

        if (contentTypeFor == null)
        {
            contentTypeFor = "application/octet-stream";
        }
        return contentTypeFor;
    }

其他地方也检查下吧。如果问题修复了，请回复一下，想换成jar包。我现在使用你的源码解决问题，项目中不想包含这样的代码（我是临时接手项目修复这个紧急问题，所以浪费了很长时间）。另外把你源码的依赖在README中写一下吧，找依赖是很烦的，谢谢。

**Comment by hongyangAndroid** [comment]
thx ~ 抱歉这么久回复，测试虽未发现该问题，不过转义一下可以使程序更加健壮，已经对外文件路径path进行了转义，稍后更新最新版本即可。
