### ISSUE TITLE
使用报错崩溃：java.lang.String okhttp3.Cookie.name()' on a null object reference

### ISSUE THREAD

**Issue by KinaZhen** [hongyangAndroid/okhttp-utils#127]
具体错误:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.Cookie.name()' on a null object reference
	at com.zhy.http.okhttp.cookie.store.MemoryCookieStore.add(MemoryCookieStore.java:28)
	at com.zhy.http.okhttp.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java:29)
	at okhttp3.internal.http.HttpEngine.receiveHeaders(HttpEngine.java:866)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:598)
	at okhttp3.RealCall.getResponse(RealCall.java:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at com.zhy.http.okhttp.log.LoggerInterceptor.intercept(LoggerInterceptor.java:46)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
	at okhttp3.RealCall.access$100(RealCall.java:30)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:831)

**Comment by skysmileereryday** [comment]
这个解决了么？

**Comment by KinaZhen** [comment]
这个出现过一次，就没出现过，我等项目不紧时，再研究下

**Comment by hongyangAndroid** [comment]
我看了下源码，`Cookie#parseAll`返回的List应该是不可能包含cookie==null这种情况的，可能由于多线程导致，目前已经加上同步机制。

**Comment by KinaZhen** [comment]
谢谢
