### ISSUE TITLE
崩溃java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

### ISSUE THREAD

**Issue by leveychen** [hongyangAndroid/okhttp-utils#128]
偶尔启动app的时候会出现下面的错误(在Application里面初始化请求一个url)。
之前都不会，就今天出现了这种情况。
(出现在退出app短时间内再开打app的时候，用System.exit(0) 退出)
用系统任务管理器结束app就不会出现这个问题
````java
FATAL EXCEPTION: OkHttp Dispatcher
Process: com.goxod.freedom, PID: 17651
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
    at com.zhy.http.okhttp.cookie.store.MemoryCookieStore.add(MemoryCookieStore.java:26)
    at com.zhy.http.okhttp.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java:29)
    at okhttp3.internal.http.HttpEngine.receiveHeaders(HttpEngine.java:866)
    at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:598)
    at okhttp3.RealCall.getResponse(RealCall.java:241)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
    at okhttp3.RealCall.access$100(RealCall.java:30)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
````

**Comment by leveychen** [comment]
在这个错误之前是请求的腾讯Bugly
[http://android.bugly.qq.com/rqd/async](url)

**Comment by skysmileereryday** [comment]
出现同样问题

**Comment by leveychen** [comment]
@skysmileereryday        你找到问题所在没。  这个问题出现几率很小，放着都没动了。

**Comment by xiaozhuge007** [comment]
@Override
    public void add(HttpUrl url, List<Cookie> cookies) {
        List<Cookie> oldCookies = allCookies.get(url.host());
        List<Cookie> needRemove = new ArrayList<>();
//
//        for (Cookie newCookie : cookies)
//        {
//            for (Cookie oldCookie : oldCookies)
//            {
//                if (newCookie.name().equals(oldCookie.name()))
//                {
//                    needRemove.add(oldCookie);
//                }
//            }
//        }
        // 1 使用Iterator提供的remove方法，用于删除当前元素
        Iterator<Cookie> itNew = cookies.iterator();
        Iterator<Cookie> it = oldCookies.iterator();
        while (itNew.hasNext()) {
            String va = itNew.next().name();
            while (va != null && it.hasNext()) {
                String v = it.next().name();
                if (v != null && va.equals(v)) {
//                    needRemove.add(it.next().name());
                    it.remove();
                }
            }
        }
//        oldCookies.removeAll(needRemove);
        oldCookies.addAll(cookies);
    }
这种错误是java源码remove（）删除的问题，改成我这样，我自己测试了好久没问题

**Comment by hongyangAndroid** [comment]
thx for  @xiaozhuge007 ，参考007的代码并做了相应修改。
