### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1

### ISSUE THREAD

**Issue by skysmileereryday** [hongyangAndroid/okhttp-utils#138]
at java.lang.System.arraycopy(Native Method)
                                                                                at java.util.ArrayList.addAll(ArrayList.java:202)
                                                                                at com.zhy.http.okhttp.cookie.store.MemoryCookieStore.add(MemoryCookieStore.java:35)
                                                                                at com.zhy.http.okhttp.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java:29)
                                                                                at okhttp3.internal.http.HttpEngine.receiveHeaders(HttpEngine.java:866)
                                                                                at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:598)
                                                                                at okhttp3.RealCall.getResponse(RealCall.java:241)
                                                                                at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
                                                                                at com.zhy.http.okhttp.log.LoggerInterceptor.intercept(LoggerInterceptor.java:46)
                                                                                at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                                                                                at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
                                                                                at okhttp3.RealCall.access$100(RealCall.java:30)
                                                                                at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
                                                                                at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:841)
                                                                            , source:LEGIT), Error(ts:1460715317079, context:java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                                                                                at java.util.ArrayList$ArrayListIterator.remove(ArrayList.java:592)
                                                                                at java.util.AbstractCollection.removeAll(AbstractCollection.java:278)
                                                                                at com.zhy.http.okhttp.cookie.store.MemoryCookieStore.add(MemoryCookieStore.java:34)
                                                                                at com.zhy.http.okhttp.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java:29)
                                                                                at okhttp3.internal.http.HttpEngine.receiveHeaders(HttpEngine.java:866)
                                                                                at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:598)
                                                                                at okhttp3.RealCall.getResponse(RealCall.java:241)
                                                                                at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
                                                                                at com.zhy.http.okhttp.log.LoggerInterceptor.intercept(LoggerInterceptor.java:46)
                                                                                at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                                                                                at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
                                                                                at okhttp3.RealCall.access$100(RealCall.java:30)
                                                                                at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
                                                                                at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:841)

**Comment by skysmileereryday** [comment]
怎么搞？

**Comment by skysmileereryday** [comment]
这个问题该如何修复？

**Comment by hongyangAndroid** [comment]
可能和[#128](https://github.com/hongyangAndroid/okhttp-utils/issues/128)遇到的问题一致，目前做了部分修改，稍后更新版本，有问题直接在#128下留言。
