### ISSUE TITLE
get请求的时候出现异常 java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by smithLiLi** [hongyangAndroid/okhttp-utils#154]
AndroidRuntime: java.util.ConcurrentModificationException
at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
at java.util.AbstractCollection.removeAll(AbstractCollection.java:277)
at  #com.zhy.http.okhttp.cookie.store.MemoryCookieStore.add(MemoryCookieStore.java:34)

有时候会出现这种异常有几次是在类MemoryCookieStore 34行 有一次在26行 看了下代码是两个for..each

**Comment by hongyangAndroid** [comment]
已经尝试修复，请使用:
```
	compile 'com.zhy:okhttputils:2.4.1'
```

**Comment by smithLiLi** [comment]
更新后 暂时没发现问题 谢谢
