### ISSUE TITLE
正常使用，还是会报如下错误，导致应用崩溃！！

### ISSUE THREAD

**Issue by KinaZhen** [hongyangAndroid/okhttp-utils#163]
=====	Device Info	=====
manufacture:HUAWEI
product:PLK-TL00
model:PLK-TL00
version.release:5.0.2
version:PLK-TL00C01B201
=====	app Info	=====
versionCode:1
versionName:1.0-debug
lastUpdateTime:2016年05月01日16点04分47秒
=====	Error Log	=====
java.lang.ArrayIndexOutOfBoundsException: src.length=1 srcPos=0 dst.length=12 dstPos=-1 length=1
	at java.lang.System.arraycopy(Native Method)
	at java.util.ArrayList.addAll(ArrayList.java:202)
	at com.zhy.http.okhttp.cookie.store.MemoryCookieStore.add(MemoryCookieStore.java:35)
	at com.zhy.http.okhttp.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java:29)
	at okhttp3.internal.http.HttpEngine.receiveHeaders(HttpEngine.java:866)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:598)
	at okhttp3.RealCall.getResponse(RealCall.java:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at com.zhy.http.okhttp.log.LoggerInterceptor.intercept(LoggerInterceptor.java:46)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
	at okhttp3.RealCall.access$100(RealCall.java:30)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:831)

**Comment by hongyangAndroid** [comment]
使用:
```
	compile 'com.zhy:okhttputils:2.4.1'
```
