### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException偶尔会报出数组越界的异常，LOG如下所示

### ISSUE THREAD

**Issue by HelloDearWorld** [hongyangAndroid/okhttp-utils#167]
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                                                                       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:579)
                                                                       at java.util.AbstractCollection.removeAll(AbstractCollection.java:277)
                                                                       at org.okhttputils.zhy.http.okhttp.cookie.store.MemoryCookieStore.add(MemoryCookieStore.java:34)
                                                                       at org.okhttputils.zhy.http.okhttp.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java:30)
                                                                       at okhttp3.internal.http.HttpEngine.receiveHeaders(HttpEngine.java:866)
                                                                       at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:598)
                                                                       at okhttp3.RealCall.getResponse(RealCall.java:241)
                                                                       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
                                                                       at org.okhttputils.zhy.http.okhttp.log.LoggerInterceptor.intercept(LoggerInterceptor.java:43)
                                                                       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                                                                       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
                                                                       at okhttp3.RealCall.access$100(RealCall.java:30)
                                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
                                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by hongyangAndroid** [comment]
版本是`2.4.1`？这个问题做过一次修复
