### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by HelloDearWorld** [hongyangAndroid/okhttp-utils#169]
Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
 at okhttp3.HttpUrl.canonicalize(HttpUrl.java:1612)
05-04 15:37:34.905 17588-17588/? W/System.err:     at okhttp3.FormBody$Builder.add(FormBody.java:110)
05-04 15:37:34.905 17588-17588/? W/System.err:     at org.zhy.http.okhttp.request.PostFormRequest.addParams(PostFormRequest.java:124)
05-04 15:37:34.905 17588-17588/? W/System.err:     at org.zhy.http.okhttp.request.PostFormRequest.buildRequestBody(PostFormRequest.java:40)
05-04 15:37:34.905 17588-17588/? W/System.err:     at org.zhy.http.okhttp.request.OkHttpRequest.generateRequest(OkHttpRequest.java:68)
05-04 15:37:34.905 17588-17588/? W/System.err:     at org.zhy.http.okhttp.request.RequestCall.generateRequest(RequestCall.java:76)
05-04 15:37:34.905 17588-17588/? W/System.err:     at org.zhy.http.okhttp.request.RequestCall.buildCall(RequestCall.java:52)
05-04 15:37:34.905 17588-17588/? W/System.err:     at org.zhy.http.okhttp.builder.PostFormBuilder.buildWithSign(PostFormBuilder.java:31)
05-04 15:37:34.905 17588-17588/? W/System.err:     at com.lingxicollege.activity.MyFavouritelistActivity.getFavouriteList(MyFavouritelistActivity.java:109)
05-04 15:37:34.906 17588-17588/? W/System.err:     at com.lingxicollege.activity.MyFavouritelistActivity.onCreate(MyFavouritelistActivity.java:73)
05-04 15:37:34.906 17588-17588/? W/System.err:     at android.app.Activity.performCreate(Activity.java:6237)
05-04 15:37:34.906 17588-17588/? W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
05-04 15:37:34.906 17588-17588/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
05-04 15:37:34.906 17588-17588/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
05-04 15:37:34.906 17588-17588/? W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
05-04 15:37:34.906 17588-17588/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
05-04 15:37:34.906 17588-17588/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
05-04 15:37:34.906 17588-17588/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
05-04 15:37:34.906 17588-17588/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
05-04 15:37:34.906 17588-17588/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-04 15:37:34.906 17588-17588/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-04 15:37:34.906 17588-17588/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by hongyangAndroid** [comment]
检查你的键值对的参数是否为null.
