### ISSUE TITLE
长时间使用，就无法获取数据

### ISSUE THREAD

**Issue by KinaZhen** [hongyangAndroid/okhttp-utils#192]
长时间使用，在有网络情况下，无法获取数据，报错：
java.net.ProtocolException: Too many follow-up requests: 21
05-19 15:10:45.502 1029-1029/ W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:289)
05-19 15:10:45.502 1029-1029/ W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
05-19 15:10:45.502 1029-1029/ W/System.err:     at com.zhy.http.okhttp.log.LoggerInterceptor.intercept(LoggerInterceptor.java:46)
05-19 15:10:45.502 1029-1029/ W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
05-19 15:10:45.502 1029-1029/ W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
05-19 15:10:45.502 1029-1029/ W/System.err:     at okhttp3.RealCall.access$100(RealCall.java:30)
05-19 15:10:45.502 1029-1029/ W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
05-19 15:10:45.502 1029-1029/ W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
05-19 15:10:45.502 1029-1029/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-19 15:10:45.502 1029-1029/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-19 15:10:45.503 1029-1029/ W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by KinaZhen** [comment]
所以请求，我并没有加 cookie,但是却自动加上 Cookie: frontend=tci7q4vmui3j47o20g7djp8sq7; frontend=deleted，正常访问时 没有frontend=deleted；搁置一段时间 有frontend=deleted。 求解
