### ISSUE TITLE
自动处理cookie报错，大神看看咋回事？

### ISSUE THREAD

**Issue by nicegoing** [hongyangAndroid/okhttp-utils#202]
请求的url是http://www.baidu.com，设置代码是在Application中
```
        CookieJarImpl cookieJar = new CookieJarImpl(new PersistentCookieStore(getApplicationContext()));
        OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .cookieJar(cookieJar)
                .addInterceptor(new LoggerInterceptor("TAG"))
                .addNetworkInterceptor(new StethoInterceptor())
                .build();
        OkHttpUtils.initClient(okHttpClient);

```
提示PersistentCookieStore这行有问题：`        prefsWriter.putString(uri.host(), TextUtils.join(",", cookies.get(uri.host()).keySet()));
`

`                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set java.util.concurrent.ConcurrentHashMap.keySet()' on a null object reference
                                                                at com.zhy.http.okhttp.cookie.store.PersistentCookieStore.add(PersistentCookieStore.java:110)
                                                                at com.zhy.http.okhttp.cookie.store.PersistentCookieStore.add(PersistentCookieStore.java:125)
                                                                at com.zhy.http.okhttp.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java:28)
                                                                at okhttp3.internal.http.HttpEngine.receiveHeaders(HttpEngine.java:866)
                                                                at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:598)
                                                                at okhttp3.RealCall.getResponse(RealCall.java:241)
                                                                at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
                                                                at com.zhy.http.okhttp.log.LoggerInterceptor.intercept(LoggerInterceptor.java:46)
                                                                at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                                                                at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
                                                                at okhttp3.RealCall.access$100(RealCall.java:30)
                                                                at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
                                                                at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                at java.lang.Thread.run(Thread.java:818)
`

**Comment by hymanAndroid** [comment]
thx，已经修复，2.5.2
