### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: src.length=1 srcPos=0 dst.length=12 dstPos=-1 length=1

### ISSUE THREAD

**Issue by zzyyppqq** [hongyangAndroid/okhttp-utils#231]
at java.lang.System.arraycopy(Native Method)
	at java.util.ArrayList.addAll(ArrayList.java:202)
	at com.zhy.http.okhttp.cookie.store.MemoryCookieStore.add(SourceFile:35)
	at com.zhy.http.okhttp.cookie.CookieJarImpl.saveFromResponse(SourceFile:29)
	at okhttp3.internal.http.HttpEngine.receiveHeaders(SourceFile:866)
	at okhttp3.internal.http.HttpEngine.readResponse(SourceFile:598)
	at okhttp3.RealCall.getResponse(SourceFile:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(SourceFile:198)
	at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:160)
	at okhttp3.RealCall.access$100(SourceFile:30)
	at okhttp3.RealCall$AsyncCall.execute(SourceFile:127)
	at okhttp3.internal.NamedRunnable.run(SourceFile:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:833)

**Comment by tdbmagci** [comment]
同问
