### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1

### ISSUE THREAD

**Issue by zzyyppqq** [hongyangAndroid/okhttp-utils#233]
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
	at java.util.ArrayList$ArrayListIterator.remove(ArrayList.java:592)
	at java.util.AbstractCollection.removeAll(AbstractCollection.java:278)
	at com.zhy.http.okhttp.cookie.store.MemoryCookieStore.add(SourceFile:34)
	at com.zhy.http.okhttp.cookie.CookieJarImpl.saveFromResponse(SourceFile:29)
	at okhttp3.internal.http.HttpEngine.receiveHeaders(SourceFile:866)
	at okhttp3.internal.http.HttpEngine.readResponse(SourceFile:598)
	at okhttp3.RealCall.getResponse(SourceFile:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(SourceFile:198)
	at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:160)
	at okhttp3.RealCall.access$100(SourceFile:30)
	at okhttp3.RealCall$AsyncCall.execute(SourceFile:127)
	at okhttp3.internal.NamedRunnable.run(SourceFile:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:833)

**Comment by hongyangAndroid** [comment]
使用的版本是？看log的行号与最新版本不一致~

**Comment by zzyyppqq** [comment]
恩，我用的版本比较低（2.3.9），我用最新版本试试，谢谢哈
