### ISSUE TITLE
crash 问题

### ISSUE THREAD

**Issue by typ0520** [hongyangAndroid/okhttp-utils#240]
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableCollection.addAll(Collections.java:932)
	at com.dx168.epmyg.utils.DXMemoryCookieStore.add(DXMemoryCookieStore.java:42)
	at com.zhy.http.okhttp.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java:29)
	at okhttp3.internal.http.HttpEngine.receiveHeaders(HttpEngine.java:866)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:598)
	at okhttp3.RealCall.getResponse(RealCall.java:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
	at okhttp3.RealCall.access$100(RealCall.java:30)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

MemoryCookieStore.java 第40行 
```oldCookies.addAll(cookies);```
建议别用addAll
```
 for (Cookie cookie : cookies) {
        oldCookies.add(cookie);
  }
```

**Comment by hongyangAndroid** [comment]
thx~ 感谢反馈~

**Comment by typ0520** [comment]
这个类又发现了一个问题 ，我把add方法里面的实现换了下

 @Override
    public void add(HttpUrl url, List<Cookie> cookies)
    {
        if (cookies == null) {
            return;
        }
        List<Cookie> oldCookies = get(url);

        for (Cookie cookie : cookies) {
            List<Cookie> preDelList = new ArrayList<>();
            for (int i = 0;i < oldCookies.size();i++) {
                Cookie oldCookie = oldCookies.get(i);
                if (cookie != null && oldCookie != null && cookie.name() != null) {
                    if (cookie.name().equals(oldCookie.name())) {
                        preDelList.add(oldCookie);
                    }
                }
            }

            oldCookies.removeAll(preDelList);
        }
//            Iterator<Cookie> itNew = cookies.iterator();
//            Iterator<Cookie> itOld = oldCookies.iterator();
//            while (itNew.hasNext())
//            {
//                String va = itNew.next().name();
//                while (va != null && itOld.hasNext())
//                {
//                    String v = itOld.next().name();
//                    if (v != null && va.equals(v))
//                    {
//                        itOld.remove();
//                    }
//                }
//            }
        for (Cookie cookie : cookies) {
            oldCookies.add(cookie);
        }
    }
