### ISSUE TITLE
post请求，不传params参数，报错。

### ISSUE THREAD

**Issue by Jacky-Xu** [hongyangAndroid/okhttp-utils#41]
Caused by: java.lang.IllegalArgumentException: the params , content , file , bytes must has one and only one .
                                                               at com.zhy.http.okhttp.request.OkHttpPostRequest.validParams(OkHttpPostRequest.java:69)
                                                               at com.zhy.http.okhttp.request.OkHttpPostRequest.buildRequestBody(OkHttpPostRequest.java:89)
                                                               at com.zhy.http.okhttp.request.OkHttpRequest.prepareInvoked(OkHttpRequest.java:51)
                                                               at com.zhy.http.okhttp.request.OkHttpRequest.invokeAsyn(OkHttpRequest.java:59)
                                                               at com.zhy.http.okhttp.request.OkHttpRequest$Builder.post(OkHttpRequest.java:231)

**Comment by hongyangAndroid** [comment]
the params , content , file , bytes must has one and only one .解释很清楚呀，必须设置一个呀；要是光url，用get好了。

**Comment by Jacky-Xu** [comment]
额。可是后台是post请求，没有任何参数，应该也有很多人跟我一样的情况吧，只是简单的post无参数请求。

**Comment by hongyangAndroid** [comment]
可以选择携带个1=1，这样的无关的参数。

**Comment by cxbiao** [comment]
随便写content =12223之类的不就好了！
