### ISSUE TITLE
OkHttpClientManager.getInstance().cancelTag("MainActivity");取消请求没用

### ISSUE THREAD

**Issue by h1091129209** [hongyangAndroid/okhttp-utils#42]
OkHttpClientManager.getInstance().cancelTag("MainActivity");

**Comment by soyoungboy** [comment]
用this,而不是字符串

**Comment by h1091129209** [comment]
直接字符串不行吗

**Comment by h1091129209** [comment]
那设置tag的时候怎么设置

**Comment by h1091129209** [comment]
new OkHttpRequest.Builder().url(uur).tag("MainActivity")

**Comment by h1091129209** [comment]
第一次取消成功了，再请求再取消就报错了
AndroidRuntime: FATAL EXCEPTION: main
                                                              android.os.NetworkOnMainThreadException
                                                                  at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1117)
                                                                  at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:926)
                                                                  at com.squareup.okhttp.Connection.closeIfOwnedBy(Connection.java:148)
                                                                  at com.squareup.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:76)
                                                                  at com.squareup.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:137)
                                                                  at com.squareup.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:134)
                                                                  at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:573)
                                                                  at com.squareup.okhttp.Dispatcher.cancel(Dispatcher.java:128)
                                                                  at com.squareup.okhttp.OkHttpClient.cancel(OkHttpClient.java:611)
                                                                  at com.zhy.http.okhttp.OkHttpClientManager.cancelTag(OkHttpClientManager.java:208)
                                                                  at com.yundcm.hhh.MainActivity$1.onClick(MainActivity.java:56)
                                                                  at android.view.View.performClick(View.java:4084)
                                                                  at android.view.View$PerformClick.run(View.java:16966)
                                                                  at android.os.Handler.handleCallback(Handler.java:615)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                  at android.os.Looper.loop(Looper.java:137)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:511)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by foreverxiongtao** [comment]
OkHttpUtils.cancelTag(this);//取消以Activity.this作为tag的请求, 该方法是成员方法，不是静态方法，好像不能这么调用，应该是 okHttpUtils.getInstance().cancelTag(this),而且好像该方法并不能取消请求
