### ISSUE TITLE
混淆后不能运行

### ISSUE THREAD

**Issue by jp1017** [hongyangAndroid/okhttp-utils#47]
我看[#18](https://github.com/hongyangAndroid/okhttp-utils/issues/18)也有该混淆问题，但是我这里还是不行，问题如下：

retrace mapping 错误信息后这样：

```java
FATAL EXCEPTION: main Process: com.inst.navigation, PID: 18379
 java.lang.NullPointerException
at com.inst.navigation.ui.activity.LoginActivity$2.
    void onError(com.squareup.okhttp.Request,java.lang.Exception)(Unknown Source)
    void onResponse(java.lang.String)
    void onResponse(java.lang.Object)
at com.inst.navigation.ui.activity.LoginActivity$2.
    void onError(com.squareup.okhttp.Request,java.lang.Exception)(Unknown Source)
    void onResponse(java.lang.String)
    void onResponse(java.lang.Object)
at com.zhy.http.okhttp.OkHttpClientManager$4.void run()(Unknown Source)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5034)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by hongyangAndroid** [comment]
```
#okhttputils
-dontwarn com.zhy.http.**
-keep class com.zhy.http.**{*;}
-keep interface com.zhy.http.**{*;}

#okhttp
-dontwarn okhttp3.**
-keep class okhttp3.**{*;}
-keep interface okhttp3.**{*;}

#okio
-dontwarn okio.**
-keep class okio.**{*;}
-keep interface okio.**{*;}
```
